# Generated by Django 3.2 on 2023-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospaas_processing', '0001_squashed_0003_remove_processingresult_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='path',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
