# Generated by Django 3.2 on 2024-11-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospaas_processing', '0002_alter_processingresult_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='ttl',
            field=models.DurationField(default=None, null=True),
        ),
    ]
