ARG BASE_IMAGE=nansencenter/geospaas:latest-slim
FROM ${BASE_IMAGE} as base

RUN apt update && \
    apt install -y \
    nco

RUN pip install --upgrade --no-cache-dir \
    'celery==5.2.*' \
    'django-celery-results==2.2.*' \
    'graypy==2.1.*' \
    'importlib-metadata==4.*' \
    'paramiko<2.9' \
    'redis==4.1.*' \
    'requests_oauthlib==1.3.*' \
    'scp==0.14.*' \
    'freezegun==1.1.*' \
    'nco'

FROM base as full

COPY idf_converter.tar.gz /tmp/idf_converter.tar.gz
RUN pip install /tmp/idf_converter.tar.gz

WORKDIR /tmp/setup
COPY setup.py README.md ./
COPY geospaas_processing ./geospaas_processing
RUN python setup.py bdist_wheel && \
    pip install -v dist/geospaas_processing-*.whl && \
    cd /tmp && rm -rf /tmp/setup/

WORKDIR /

ENTRYPOINT ["celery"]
CMD ["worker", "-A", "geospaas_processing.tasks", "-l", "info"]
