---
name: "Unit tests and builds"
on: push
env:
  BASE_IMAGE_NAME: "${{ secrets.DOCKER_ORG }}/geospaas:2.4.0-slim"
  IMAGE_NAME_WORKER: "${{ secrets.DOCKER_ORG }}/geospaas_processing_worker"
  IMAGE_NAME_CLI: "${{ secrets.DOCKER_ORG }}/geospaas_processing_cli"
  IDF_CONVERTER_VERSION: '0.0.158'
jobs:
  tests:
    runs-on: 'ubuntu-20.04'
    env:
      GEOSPAAS_DB_HOST: 'db'
      GEOSPAAS_DB_USER: 'test'
      GEOSPAAS_DB_PASSWORD: ${{ secrets.GEOSPAAS_DB_PASSWORD }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Create test docker network'
        run: docker network create testing

      - name: 'Start testing database'
        run: >
             docker run -d --rm
             --network testing
             --name "$GEOSPAAS_DB_HOST"
             -e "POSTGRES_USER=$GEOSPAAS_DB_USER" -e "POSTGRES_PASSWORD=$GEOSPAAS_DB_PASSWORD"
             'postgis/postgis:12-3.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-testing-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-testing-

      - name: Build testing image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_worker
          target: base
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME_WORKER }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
             docker run --rm
             --network testing
             -v "$(pwd):/src"
             -e "GITHUB_ACTIONS=$GITHUB_ACTIONS"
             -e "GITHUB_REF=$GITHUB_REF"
             -e "GITHUB_SHA=$GITHUB_SHA"
             -e "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
             -e "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
             -e "GITHUB_RUN_ID=$GITHUB_RUN_ID"
             -e "GITHUB_TOKEN=$GITHUB_TOKEN"
             -e "GEOSPAAS_DB_HOST=$GEOSPAAS_DB_HOST"
             -e "GEOSPAAS_DB_USER=$GEOSPAAS_DB_USER"
             -e "GEOSPAAS_DB_PASSWORD=$GEOSPAAS_DB_PASSWORD"
             "${IMAGE_NAME_WORKER}"
             bash -c "coverage run --source=geospaas_processing /src/runtests.py && coveralls"

      - name: 'Stop testing database'
        run: docker stop "$GEOSPAAS_DB_HOST"


  build_worker_image:
    runs-on: 'ubuntu-20.04'
    needs: 'tests'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: "Extract tag name"
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]];then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG='tmp'
          fi
          echo "::set-output name=VERSION::${TAG}"

      - name: Get IDF converter
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: >
             curl -L -o ./idf_converter.tar.gz
             -H "Authorization: token ${API_TOKEN_GITHUB}"
             -H 'Accept: application/vnd.github.v3.raw'
             "https://api.github.com/repos/nansencenter/idf-converter/contents/idf_converter-${IDF_CONVERTER_VERSION}.tar.gz"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-worker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-worker-
            ${{ runner.os }}-buildx-testing-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_worker
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}
          push: ${{ startsWith(github.event.ref, 'refs/tags/') }}
          tags: |
            ${{ env.IMAGE_NAME_WORKER }}:latest
            ${{ env.IMAGE_NAME_WORKER }}:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


  build_cli_image:
    runs-on: 'ubuntu-20.04'
    needs: 'tests'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: "Extract tag name"
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]];then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG='tmp'
          fi
          echo "::set-output name=VERSION::${TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cli-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-cli-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_cli
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}
          push: ${{ startsWith(github.event.ref, 'refs/tags/') }}
          tags: |
            ${{ env.IMAGE_NAME_CLI }}:latest
            ${{ env.IMAGE_NAME_CLI }}:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


  publish_python_package:
    runs-on: 'ubuntu-20.04'
    needs: 'tests'
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Build Python package'
        run: >
             docker run --rm
             -v "$(pwd):/src"
             -e "GEOSPAAS_PROCESSING_RELEASE=${{ github.event.tag_name }}"
             "${BASE_IMAGE_NAME}"
             python setup.py sdist bdist_wheel

      - name: 'Deploy package to the Github release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/*'
          file_glob: true
          tag: ${{ github.event.tag_name }}
...